LW/legged_lab_v2/leg_loco:
  model_name: "policy.pt"
  num_observations:  45   # 3 3 3 10 10 10 2 3
  observations: ["ang_vel", "gravity_vec", "commands", "dof_pos", "dof_vel", "actions", "gait_phase", "gait_command"]
  observations_history: []  # 0 is the latest observation
  observations_history_priority: "time"  # "time" or "term" priority
  clip_obs: 100.0
  clip_actions_lower: [-100.0, -100.0,
                       -100.0, -100.0,
                       -100.0, -100.0,
                       -100.0, -100.0,
                       -100.0, -100.0]
  clip_actions_upper: [100.0, 100.0,
                       100.0, 100.0,
                       100.0, 100.0,
                       100.0, 100.0,
                       100.0, 100.0]
  rl_kp: [70.0, 70.0,
          70.0, 70.0,
          70.0, 70.0,
          8.0, 8.0,
          0.0, 0.0]
  rl_kd: [3.0, 3.0,
          3.0, 3.0,
          3.0, 3.0,
          0.3, 0.3,
          0.4, 0.4]
  fixed_kp: [80.0, 80.0, 
             50.0, 50.0,
             50.0, 50.0,
             20.0, 20.0,
             20.0, 20.0]
  fixed_kd: [3.0, 3.0,
             3.0, 3.0,
             3.0, 3.0, 
             3.0, 3.0,
             3.0, 3.0]
  num_of_dofs: 10
  action_scale: [0.125, 0.125,
                 0.25, 0.25,
                 0.25, 0.25,
                 0.25, 0.25,
                 1.0, 1.0]
  wheel_indices: [8, 9]
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [1.0, 1.0, 1.0]
  torque_limits: [120.0, 120.0,
                  120.0, 120.0,
                  120.0, 120.0, 
                  27.0,  27.0,
                  40.0,  40.0]
  default_dof_pos: [0.0, 0.0,
                    0.3491, 0.3491,
                    2.269, 2.269,
                    0.5236, 0.5236,
                    0.0, 0.0]
  gait_command: [2.0, 0.5, 0.5, 0.25]
  vel_command: [0.7, 0.5, 1.0]
  joint_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]